apiVersion: v1
kind: Pod
metadata:
    name: client-pod
    labels:
        component: web
spec:
    containers:
        - name: client
          image: xlreon/docker-client
          ports: 
            - containerPort: 3000
